// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace, KvNamespace as __TelnyxKvNamespace } from "@telnyx/edge-runtime";

declare global {
  interface Env {
    SITES: __TelnyxActorNamespace;
    REGIONS: __TelnyxActorNamespace;
    CACHE: __TelnyxKvNamespace;
    SECRETS: { get(binding: "TELNYX_PUBLIC_KEY" | "MCP_TOKEN" | "OPS_TOKEN" | "PIN_PEPPER" | "ONCALL_NUMBER" | "SEED_LOCAL"): Promise<string> };
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    SITES: __TelnyxActorNamespace;
    REGIONS: __TelnyxActorNamespace;
    CACHE: __TelnyxKvNamespace;
    SECRETS: { get(binding: "TELNYX_PUBLIC_KEY" | "MCP_TOKEN" | "OPS_TOKEN" | "PIN_PEPPER" | "ONCALL_NUMBER" | "SEED_LOCAL"): Promise<string> };
  }
}

export {};
