// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace } from "@telnyx/edge-runtime";
import type { SiteActor, RegionActor } from "./src/index";

declare global {
  interface Env {
    SITES: __TelnyxActorNamespace<SiteActor>;
    REGIONS: __TelnyxActorNamespace<RegionActor>;
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    SITES: __TelnyxActorNamespace<SiteActor>;
    REGIONS: __TelnyxActorNamespace<RegionActor>;
  }
}

export {};
