// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace } from "@telnyx/edge-runtime";
import type { SiteState, RegionState } from "./src/index";

declare global {
  interface Env {
    SITES: __TelnyxActorNamespace<SiteState>;
    REGIONS: __TelnyxActorNamespace<RegionState>;
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    SITES: __TelnyxActorNamespace<SiteState>;
    REGIONS: __TelnyxActorNamespace<RegionState>;
  }
}

export {};
