// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace, KvNamespace as __TelnyxKvNamespace } from "@telnyx/edge-runtime";
import type { ProbeActorV2 } from "./src/index";

declare global {
  interface Env {
    PROBE: __TelnyxActorNamespace<ProbeActorV2>;
    CACHE: __TelnyxKvNamespace;
    SECRETS: { get(binding: "TELNYX_PUBLIC_KEY" | "MCP_TOKEN" | "OPS_TOKEN"): Promise<string> };
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    PROBE: __TelnyxActorNamespace<ProbeActorV2>;
    CACHE: __TelnyxKvNamespace;
    SECRETS: { get(binding: "TELNYX_PUBLIC_KEY" | "MCP_TOKEN" | "OPS_TOKEN"): Promise<string> };
  }
}

export {};
