import type { DemoGuide, GuideScenario } from "./guide";

export const DEMO_AGENT_ID = "assistant-a2d301b3-f112-48f6-84c8-9e4d052cf3b7";

const WIDGET_SCRIPT_URL = "https://unpkg.com/@telnyx/ai-agent-widget@0.36.0";
const GUIDE_FALLBACK = "PIN: see the README reviewer guide";

const CSS = [
  ":root{color-scheme:dark;",
  "--bg:#070B10;--surface:rgba(15,22,31,.72);--line:rgba(148,163,184,.14);",
  "--text:#E6EDF3;--muted:#8B98A5;--dim:#5B6B7B;--accent:#22D3EE;",
  "--ok:#34D399;--p2:#F59E0B;--p1:#F43F5E;--quiet:rgb(51,65,85);--radius:16px}",
  "*,*::before,*::after{box-sizing:border-box}",
  "html{background:var(--bg)}",
  "body{margin:0;background:var(--bg);color:var(--text);",
  "font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;",
  "line-height:1.55;min-height:100vh;position:relative;overflow-x:hidden}",
  "body::before{content:'';position:fixed;inset:0;pointer-events:none;z-index:0;",
  "background:radial-gradient(60rem 60rem at 12% -8%,rgba(34,211,238,.08),transparent 60%),",
  "radial-gradient(50rem 50rem at 88% 108%,rgba(99,102,241,.07),transparent 60%)}",
  "body::after{content:'';position:fixed;inset:0;pointer-events:none;z-index:0;",
  "background-image:linear-gradient(rgba(255,255,255,.03) 1px,transparent 1px),",
  "linear-gradient(90deg,rgba(255,255,255,.03) 1px,transparent 1px);",
  "background-size:32px 32px}",
  ".mono,.kNum,.clock,.cardNum,code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;",
  "font-variant-numeric:tabular-nums}",
  "h1,h2,h3{margin:0;font-weight:650;letter-spacing:.01em}",
  "h2{font-size:1.05rem;color:var(--muted);text-transform:uppercase;letter-spacing:.12em}",
  "h3{font-size:1.05rem}",
  "p{margin:.5rem 0}",
  "section{position:relative;z-index:1}",
  "/* header */",
  ".top{position:sticky;top:0;z-index:20;display:flex;align-items:center;gap:1rem;",
  "justify-content:space-between;padding:.8rem 1.5rem;border-bottom:1px solid var(--line);",
  "background:rgba(7,11,16,.78);backdrop-filter:blur(12px)}",
  ".mark{font-size:1.02rem;letter-spacing:.22em;color:var(--text)}",
  ".sub{display:block;font-size:.74rem;color:var(--dim);letter-spacing:.06em}",
  ".topRight{display:flex;align-items:center;gap:.7rem;flex-wrap:wrap}",
  ".live{display:inline-flex;align-items:center;gap:.4rem;border:1px solid rgba(52,211,153,.35);",
  "color:var(--ok);border-radius:999px;padding:.18rem .65rem;font-size:.74rem;font-weight:700;letter-spacing:.14em}",
  ".liveDot{width:8px;height:8px;border-radius:50%;background:var(--ok);",
  "box-shadow:0 0 8px rgba(52,211,153,.8);animation:pulseDot 1.6s ease-in-out infinite}",
  ".clock{color:var(--muted);font-size:.86rem}",
  ".modeChip{border:1px solid var(--line);color:var(--muted);border-radius:999px;",
  "padding:.18rem .6rem;font-size:.74rem}",
  "/* layout */",
  ".wrap{max-width:85rem;margin:0 auto;padding:1.5rem;display:grid;gap:1.25rem;",
  "grid-template-columns:1fr}",
  "@media (min-width:64em){.wrap{grid-template-columns:5fr 7fr;align-items:start}}",
  ".panel{background:var(--surface);backdrop-filter:blur(12px);border:1px solid var(--line);",
  "border-radius:var(--radius);padding:1.1rem 1.2rem 1.25rem;",
  "box-shadow:0 8px 32px rgba(2,6,12,.5)}",
  ".panel h2{margin-bottom:.9rem}",
  "/* orb */",
  ".orbWrap{display:flex;justify-content:center;padding:1.6rem 0 .8rem}",
  ".orb{position:relative;width:8.5rem;height:8.5rem;border-radius:50%;border:none;cursor:pointer;",
  "background:radial-gradient(circle at 50% 40%,rgba(34,211,238,.28),rgba(34,211,238,.06) 60%,transparent);",
  "display:flex;align-items:center;justify-content:center;color:var(--accent);",
  "transition:transform .25s ease, box-shadow .25s ease}",
  ".orb:hover{transform:scale(1.04);box-shadow:0 0 34px rgba(34,211,238,.28)}",
  ".orb:focus-visible{outline:2px solid var(--accent);outline-offset:4px}",
  ".ring{position:absolute;inset:0;border-radius:50%;border:1px solid rgba(34,211,238,.5);",
  "animation:ringOut 2.6s ease-out infinite;opacity:0}",
  ".ring.r2{animation-delay:.85s}",
  ".ring.r3{animation-delay:1.7s}",
  ".orb svg{width:2.6rem;height:2.6rem;filter:drop-shadow(0 0 6px rgba(34,211,238,.65))}",
  ".orbCap{text-align:center;color:var(--muted);font-size:.86rem;min-height:2.4em}",
  "/* cards */",
  ".cards{display:flex;flex-direction:column;gap:.9rem;margin-top:1rem}",
  ".card{position:relative;border:1px solid var(--line);border-radius:12px;padding:.85rem .95rem;",
  "background:rgba(11,17,25,.55)}",
  ".cardNum{position:absolute;top:-.55rem;left:.8rem;background:var(--accent);color:rgb(4,20,26);",
  "border-radius:8px;padding:.05rem .45rem;font-size:.78rem;font-weight:700}",
  ".card h3{margin:.35rem 0 .3rem;font-size:.98rem}",
  ".say{font-size:.88rem;color:var(--text)}",
  ".say q{color:#9fd8e6}",
  ".watch{font-size:.82rem;color:var(--dim)}",
  ".pin-chip{margin-top:.5rem;border:1px dashed rgba(34,211,238,.45);color:var(--accent);",
  "background:rgba(34,211,238,.07);border-radius:999px;padding:.28rem .7rem;cursor:pointer;",
  "font-size:.82rem;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}",
  ".pin-chip:hover{background:rgba(34,211,238,.16)}",
  ".pin-miss{display:inline-block;margin-top:.5rem;color:var(--dim);font-size:.82rem;",
  "border:1px dashed rgba(139,152,165,.35);border-radius:999px;padding:.28rem .7rem}",
  "/* ribbon */",
  ".ribbon{margin-top:1.4rem;border-top:1px solid var(--line);padding-top:1rem}",
  ".ribbonTitle{font-size:.74rem;color:var(--dim);text-transform:uppercase;letter-spacing:.14em;margin:0 0 .7rem}",
  ".flow{list-style:none;display:flex;gap:.4rem;margin:0;padding:0;flex-wrap:wrap;",
  "align-items:stretch;justify-content:space-between}",
  ".flow li{flex:1 1 0;min-width:6.5rem;position:relative;text-align:center;font-size:.72rem;",
  "color:var(--muted);display:flex;flex-direction:column;align-items:center;gap:.3rem;padding:.2rem}",
  ".flow li:not(:last-child)::before{content:'';position:absolute;top:1.05rem;left:calc(50% + 1.4rem);",
  "right:calc(-50% + 1.4rem);height:1px;background:linear-gradient(90deg,rgba(34,211,238,.4),rgba(99,102,241,.35))}",
  ".flow li:not(:last-child)::after{content:'';position:absolute;top:.98rem;left:calc(50% + 1.4rem);",
  "width:5px;height:5px;border-radius:50%;background:var(--accent);",
  "box-shadow:0 0 6px rgba(34,211,238,.9);animation:flowDot 2.8s linear infinite}",
  ".flow li:nth-child(2)::after{animation-delay:.7s}",
  ".flow li:nth-child(3)::after{animation-delay:1.4s}",
  ".flow li:nth-child(4)::after{animation-delay:2.1s}",
  ".flow svg{width:1.5rem;height:1.5rem;color:var(--accent)}",
  ".flow small{display:block;color:var(--dim);font-size:.66rem}",
  "/* board */",
  ".boardHead{display:flex;align-items:center;gap:.6rem}",
  ".stale{border:1px solid rgba(245,158,11,.55);color:var(--p2);border-radius:999px;",
  "padding:.14rem .55rem;font-size:.72rem;font-weight:700}",
  ".kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:.7rem;margin:.9rem 0}",
  "@media (max-width:40em){.kpis{grid-template-columns:repeat(2,1fr)}}",
  ".kpi{border:1px solid var(--line);border-radius:12px;padding:.55rem .7rem;background:rgba(11,17,25,.55)}",
  ".kLabel{display:block;font-size:.66rem;color:var(--dim);text-transform:uppercase;letter-spacing:.1em}",
  ".kNum{display:block;font-size:1.25rem;color:var(--text);margin-top:.1rem}",
  ".regions{display:grid;grid-template-columns:repeat(2,1fr);gap:.8rem}",
  "@media (max-width:40em){.regions{grid-template-columns:1fr}}",
  ".regionCard{border:1px solid var(--line);border-radius:12px;padding:.7rem .8rem;background:rgba(11,17,25,.5)}",
  ".regionCard.quiet{border-color:rgba(51,65,85,.6);color:var(--dim)}",
  ".regionCard.p2{border-color:rgba(245,158,11,.6)}",
  ".regionCard.p1{border-color:rgba(244,63,94,.65);animation:p1Glow 3.2s ease-in-out infinite}",
  ".regionCard.upgraded{animation:borderFlash 1.6s ease-out}",
  ".regionCard.flash{animation:rowFlash 1.2s ease-out}",
  ".regionHead{display:flex;justify-content:space-between;align-items:center;gap:.5rem}",
  ".regionName{font-size:.9rem;font-weight:650}",
  ".badge{font-size:.66rem;font-weight:800;letter-spacing:.12em;border-radius:6px;",
  "padding:.14rem .45rem;border:1px solid var(--line);color:var(--dim)}",
  ".regionCard.p2 .badge{color:var(--p2);border-color:rgba(245,158,11,.6)}",
  ".regionCard.p1 .badge{color:var(--p1);border-color:rgba(244,63,94,.65)}",
  ".incLine,.siteLine{margin:.42rem 0;font-size:.78rem;color:var(--muted)}",
  ".incLine .mono,.siteLine .mono{color:var(--text)}",
  ".prio{display:inline-block;border-radius:5px;padding:.02rem .34rem;font-size:.66rem;font-weight:800}",
  ".prio.P1{color:var(--p1);border:1px solid rgba(244,63,94,.55)}",
  ".prio.P2{color:var(--p2);border:1px solid rgba(245,158,11,.55)}",
  ".feed{list-style:none;margin:.4rem 0 0;padding:0;display:flex;flex-direction:column;gap:.3rem}",
  ".feed li{font-size:.76rem;color:var(--muted);border-left:2px solid rgba(34,211,238,.4);",
  "padding:.22rem .5rem;background:rgba(11,17,25,.45);border-radius:0 8px 8px 0}",
  ".feed li.fresh{animation:fadeIn .9s ease-out}",
  ".panelFoot{margin:1rem 0 0;font-size:.72rem;color:var(--dim)}",
  "/* drawer */",
  ".drawer{position:relative;z-index:10;max-width:85rem;margin:0 auto 2rem;padding:0 1.5rem}",
  ".drawer summary{cursor:pointer;color:var(--dim);font-size:.8rem;width:max-content}",
  ".drawerBody{border:1px solid var(--line);border-radius:var(--radius);margin-top:.6rem;padding:1rem 1.1rem;",
  "background:var(--surface);backdrop-filter:blur(12px);display:flex;flex-direction:column;gap:.8rem}",
  ".drawerBody label{font-size:.8rem;color:var(--muted);display:flex;flex-direction:column;gap:.3rem}",
  ".drawerBody input{background:rgba(7,11,16,.8);border:1px solid var(--line);color:var(--text);",
  "border-radius:8px;padding:.45rem .6rem;font-size:.86rem;width:min(22rem,100%)}",
  ".opsBtns{display:flex;gap:.6rem;flex-wrap:wrap}",
  ".opsBtns button{border:1px solid rgba(34,211,238,.4);color:var(--accent);background:rgba(34,211,238,.07);",
  "border-radius:10px;padding:.42rem .8rem;font-size:.8rem;cursor:pointer}",
  ".opsBtns button:hover{background:rgba(34,211,238,.16)}",
  ".opsOut{margin:0;font-size:.74rem;color:var(--muted);white-space:pre-wrap;word-break:break-word;",
  "min-height:1.4em}",
  ".foot{position:relative;z-index:1;max-width:85rem;margin:0 auto;padding:0 1.5rem 2.2rem;",
  "color:var(--dim);font-size:.76rem;text-align:center}",
  "/* motion */",
  "@keyframes pulseDot{0%,100%{transform:scale(1);opacity:1}50%{transform:scale(1.45);opacity:.55}}",
  "@keyframes ringOut{0%{transform:scale(.5);opacity:.9}100%{transform:scale(1.5);opacity:0}}",
  "@keyframes flowDot{0%{left:calc(50% + 1.4rem);opacity:0}12%{opacity:1}",
  "88%{opacity:1}100%{left:calc(100% - 1.4rem);opacity:0}}",
  "@keyframes p1Glow{0%,100%{box-shadow:0 0 0 0 rgba(244,63,94,0)}",
  "50%{box-shadow:0 0 1.6rem .14rem rgba(244,63,94,.24)}}",
  "@keyframes borderFlash{0%{box-shadow:0 0 0 0 rgba(244,63,94,.55);border-color:var(--p1)}",
  "100%{box-shadow:0 0 0 0 rgba(244,63,94,0)}}",
  "@keyframes rowFlash{0%{box-shadow:0 0 0 .18rem rgba(34,211,238,.5);border-color:var(--accent)}",
  "100%{box-shadow:0 0 0 0 rgba(34,211,238,0)}}",
  "@keyframes fadeIn{0%{opacity:0;transform:translateY(-.3rem)}100%{opacity:1;transform:none}}",
  "@media (prefers-reduced-motion: reduce){",
  "*,*::before,*::after{animation:none !important;transition:none !important}}",
].join("\n");

const ORB_SVG = [
  "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7'",
  " stroke-linecap='round' stroke-linejoin='round' aria-hidden='true'>",
  "<path d='M12 3a3 3 0 0 1 3 3v5a3 3 0 0 1-6 0V6a3 3 0 0 1 3-3z'/>",
  "<path d='M5 11a7 7 0 0 0 14 0'/>",
  "<path d='M12 18v3'/>",
  "</svg>",
].join("");

const FLOW_SVGS = [
  "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7' aria-hidden='true'><circle cx='12' cy='8' r='3.4'/><path d='M5 20a7 7 0 0 1 14 0'/></svg>",
  "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7' stroke-linecap='round' aria-hidden='true'><path d='M3 12h3l2-6 3 12 3-9 2 3h4'/></svg>",
  "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7' stroke-linecap='round' aria-hidden='true'><rect x='4' y='4' width='16' height='16' rx='3'/><path d='M9 9h6M9 13h6M9 17h3'/></svg>",
  "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7' stroke-linecap='round' aria-hidden='true'><ellipse cx='12' cy='6' rx='7' ry='3'/><path d='M5 6v12c0 1.7 3.1 3 7 3s7-1.3 7-3V6'/><path d='M5 12c0 1.7 3.1 3 7 3s7-1.3 7-3'/></svg>",
  "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7' stroke-linecap='round' aria-hidden='true'><rect x='3' y='5' width='18' height='12' rx='2'/><path d='M8 21h8M12 17v4'/></svg>",
];

const FLOW_STEPS = [
  "Caller",
  "Telnyx Voice AI<small>Sanad · workflow</small>",
  "Edge Function<small>dynamic variables · tools · MCP</small>",
  "Stateful Actors + KV",
  "NOC board",
];

function flowList(): string {
  const items = FLOW_STEPS.map(
    (step, i) => `<li>${FLOW_SVGS[i]}<span>${step}</span></li>`,
  );
  return `<ol class="flow">${items.join("")}</ol>`;
}

const APP_JS = [
  "(function () {",
  "'use strict';",
  "var POLL_MS = 5e3, FETCH_MS = 8e3, FLASH_MS = 12e2, CLOCK_MS = 1e3;",
  "var board = null, prevByRegion = {}, prioByRegion = {}, generatedMs = 0;",
  "function el(tag, cls, text) {",
  "  var node = document.createElement(tag);",
  "  if (cls) node.className = cls;",
  "  if (text !== undefined && text !== null) node.textContent = String(text);",
  "  return node;",
  "}",
  "function byId(id) { return document.getElementById(id); }",
  "/* clock */",
  "var clockEl = byId('clock');",
  "var riyadh = new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Riyadh',",
  "  hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false });",
  "function updateAge() {",
  "  if (board === null) return;",
  "  var ageS = Math.max(0, Math.round((Date.now() - generatedMs) / 1e3));",
  "  byId('kAge').textContent = 'updated ' + ageS + 's ago';",
  "}",
  "setInterval(function () {",
  "  if (clockEl) clockEl.textContent = riyadh.format(new Date());",
  "  updateAge();",
  "}, CLOCK_MS);",
  "if (clockEl) clockEl.textContent = riyadh.format(new Date());",
  "/* pin chips: click to copy */",
  "Array.prototype.forEach.call(document.querySelectorAll('.pin-chip'), function (chip) {",
  "  var pin = chip.getAttribute('data-pin') || '';",
  "  chip.addEventListener('click', function () {",
  "    var restore = function () {",
  "      chip.textContent = 'PIN ' + pin + ' · click to copy';",
  "      chip.classList.remove('copied');",
  "    };",
  "    var write = function (value) {",
  "      chip.textContent = 'copied ✓';",
  "      chip.classList.add('copied');",
  "      setTimeout(restore, FLASH_MS);",
  "    };",
  "    var fallback = function () {",
  "      var area = el('textarea');",
  "      area.value = pin;",
  "      area.setAttribute('readonly', '');",
  "      area.style.position = 'fixed';",
  "      area.style.opacity = '0';",
  "      document.body.appendChild(area);",
  "      area.select();",
  "      try { document.execCommand('copy'); } catch (err) { /* none */ }",
  "      document.body.removeChild(area);",
  "      write(pin);",
  "    };",
  "    if (navigator.clipboard && navigator.clipboard.writeText) {",
  "      navigator.clipboard.writeText(pin).then(write, fallback);",
  "    } else { fallback(); }",
  "  });",
  "});",
  "/* voice orb starts the widget's own launcher */",
  "var orb = byId('orb'), cap = byId('orbCap');",
  "orb.addEventListener('click', function () {",
  "  var host = document.querySelector('telnyx-ai-agent');",
  "  var launcher = host && host.shadowRoot ? host.shadowRoot.querySelector('button') : null;",
  "  if (launcher) launcher.click();",
  "  cap.textContent = launcher",
  "    ? 'Connecting… allow the microphone, then speak to Sanad.'",
  "    : 'Connecting… the voice widget is still loading — one moment.';",
  "});",
  "/* board rendering */",
  "function incidentBadge(inc) {",
  "  return inc === null ? 'QUIET' : 'INCIDENT ' + inc.priority;",
  "}",
  "function siteLines(container, sites, region) {",
  "  for (var i = 0; i < sites.length; i++) {",
  "    var site = sites[i];",
  "    if (site.region !== region || site.open_ticket === null) continue;",
  "    var line = el('p', 'siteLine');",
  "    line.appendChild(el('span', 'mono', site.site_id));",
  "    line.appendChild(el('span', '', ' ' + site.label));",
  "    var right = el('span', '');",
  "    right.appendChild(el('span', 'mono', ' · ' + site.open_ticket.id + ' '));",
  "    right.appendChild(el('span', 'prio ' + site.open_ticket.priority, site.open_ticket.priority));",
  "    right.appendChild(el('span', '', ' opened ' + site.open_ticket.opened_local));",
  "    line.appendChild(right);",
  "    container.appendChild(line);",
  "  }",
  "}",
  "function renderRegions(next) {",
  "  var host = byId('regions');",
  "  while (host.firstChild) host.removeChild(host.firstChild);",
  "  for (var r = 0; r < next.regions.length; r++) {",
  "    var region = next.regions[r];",
  "    var inc = region.incident;",
  "    var state = inc === null ? 'quiet' : (inc.priority === 'P1' ? 'p1' : 'p2');",
  "    var card = el('article', 'regionCard ' + state);",
  "    var head = el('div', 'regionHead');",
  "    head.appendChild(el('span', 'regionName', region.label));",
  "    head.appendChild(el('span', 'badge', incidentBadge(inc)));",
  "    card.appendChild(head);",
  "    if (inc !== null) {",
  "      var incLine = el('p', 'incLine');",
  "      incLine.appendChild(el('span', 'mono', inc.id));",
  "      incLine.appendChild(el('span', '',",
  "        ' · ' + inc.site_count + ' branches affected · declared ' + inc.declared_local));",
  "      card.appendChild(incLine);",
  "    } else {",
  "      card.appendChild(el('p', 'incLine', 'all sites nominal'));",
  "    }",
  "    siteLines(card, next.sites, region.region);",
  "    var sig = signature(region, next.sites);",
  "    if (prevByRegion[region.region] !== undefined && prevByRegion[region.region] !== sig) {",
  "      card.classList.add('flash');",
  "      setTimeout(function (node) { return function () { node.classList.remove('flash'); }; }(card), FLASH_MS);",
  "    }",
  "    var prevPrio = prioByRegion[region.region];",
  "    if (prevPrio === 'P2' && inc !== null && inc.priority === 'P1') {",
  "      card.classList.add('upgraded');",
  "    }",
  "    prioByRegion[region.region] = inc === null ? null : inc.priority;",
  "    prevByRegion[region.region] = sig;",
  "    host.appendChild(card);",
  "  }",
  "}",
  "function signature(region, sites) {",
  "  var parts = [region.label];",
  "  if (region.incident !== null) {",
  "    parts.push(region.incident.id, region.incident.priority,",
  "      String(region.incident.site_count), region.incident.declared_local);",
  "  } else { parts.push('-'); }",
  "  for (var i = 0; i < sites.length; i++) {",
  "    var site = sites[i];",
  "    if (site.region !== region.region || site.open_ticket === null) continue;",
  "    parts.push(site.site_id + ':' + site.open_ticket.id + ':' + site.open_ticket.priority);",
  "  }",
  "  return parts.join('|');",
  "}",
  "/* event feed: client-side diff of consecutive board snapshots */",
  "var feedLines = [];",
  "function diffLines(prev, next) {",
  "  var lines = [];",
  "  for (var r = 0; r < next.regions.length; r++) {",
  "    var region = next.regions[r];",
  "    var before = null;",
  "    for (var q = 0; q < prev.regions.length; q++) {",
  "      if (prev.regions[q].region === region.region) { before = prev.regions[q]; break; }",
  "    }",
  "    var prevInc = before === null ? null : before.incident;",
  "    var inc = region.incident;",
  "    if (prevInc === null && inc !== null) {",
  "      lines.push(inc.id + ' declared ' + inc.priority + ' · ' + region.label);",
  "    }",
  "    if (prevInc !== null && inc === null) {",
  "      lines.push(prevInc.id + ' resolved');",
  "    }",
  "    if (prevInc !== null && inc !== null && prevInc.priority !== inc.priority) {",
  "      lines.push(inc.id + (inc.priority === 'P1'",
  "        ? ' raised to P1 · ' + inc.site_count + ' branches'",
  "        : ' lowered to ' + inc.priority));",
  "    }",
  "  }",
  "  for (var s = 0; s < next.sites.length; s++) {",
  "    var site = next.sites[s];",
  "    var prevSite = null;",
  "    for (var t = 0; t < prev.sites.length; t++) {",
  "      if (prev.sites[t].site_id === site.site_id) { prevSite = prev.sites[t]; break; }",
  "    }",
  "    var prevTicket = prevSite === null ? null : prevSite.open_ticket;",
  "    var ticket = site.open_ticket;",
  "    if (ticket !== null && (prevTicket === null || prevTicket.id !== ticket.id)) {",
  "      lines.push(ticket.id + ' opened · ' + site.site_id + ' · ' + ticket.priority);",
  "    }",
  "    if (ticket === null && prevTicket !== null) {",
  "      lines.push(prevTicket.id + ' resolved · ' + site.site_id);",
  "    }",
  "  }",
  "  return lines;",
  "}",
  "function renderFeed(newCount) {",
  "  var host = byId('feed');",
  "  while (host.firstChild) host.removeChild(host.firstChild);",
  "  for (var i = 0; i < feedLines.length && i < 8; i++) {",
  "    host.appendChild(el('li', i < newCount ? 'fresh' : '', feedLines[i]));",
  "  }",
  "}",
  "function applyBoard(prev, next) {",
  "  var incidents = 0, p1 = 0, tickets = 0, r, s;",
  "  for (r = 0; r < next.regions.length; r++) {",
  "    if (next.regions[r].incident !== null) {",
  "      incidents++;",
  "      if (next.regions[r].incident.priority === 'P1') p1++;",
  "    }",
  "  }",
  "  for (s = 0; s < next.sites.length; s++) {",
  "    if (next.sites[s].open_ticket !== null) tickets++;",
  "  }",
  "  byId('kInc').textContent = String(incidents);",
  "  byId('kP1').textContent = String(p1);",
  "  byId('kTix').textContent = String(tickets);",
  "  byId('modeChip').textContent = 'actors: ' + next.actor_mode;",
  "  renderRegions(next);",
  "  if (prev === null) {",
  "    feedLines.unshift('live board synced · ' + next.sites.length + ' sites watched');",
  "    renderFeed(1);",
  "  } else {",
  "    var fresh = diffLines(prev, next);",
  "    for (var i = fresh.length - 1; i >= 0; i--) {",
  "      if (feedLines.indexOf(fresh[i]) === -1) feedLines.unshift(fresh[i]);",
  "    }",
  "    feedLines = feedLines.slice(0, 8);",
  "    renderFeed(fresh.length);",
  "  }",
  "  updateAge();",
  "}",
  "/* polling: no overlap, hard timeout, never blank */",
  "var staleBadge = byId('staleBadge');",
  "var polling = false;",
  "function poll() {",
  "  if (polling) { setTimeout(poll, POLL_MS); return; }",
  "  polling = true;",
  "  var ctrl = new AbortController();",
  "  var timer = setTimeout(function () { ctrl.abort(); }, FETCH_MS);",
  "  fetch('/ops/board', { signal: ctrl.signal, headers: { accept: 'application/json' } })",
  "    .then(function (res) {",
  "      if (!res.ok) throw new Error('http ' + res.status);",
  "      return res.json();",
  "    })",
  "    .then(function (next) {",
  "      var prev = board;",
  "      board = next;",
  "      generatedMs = Date.parse(next.generated_at) || Date.now();",
  "      applyBoard(prev, next);",
  "      if (staleBadge) staleBadge.hidden = true;",
  "    })",
  "    .catch(function () { if (staleBadge) staleBadge.hidden = false; })",
  "    .then(function () {",
  "      clearTimeout(timer);",
  "      polling = false;",
  "      setTimeout(poll, POLL_MS);",
  "    });",
  "}",
  "poll();",
  "/* operator drawer: token lives in sessionStorage only, sent as a bearer */",
  "var TOKEN_KEY = 'nocOpsToken';",
  "var tokenInput = byId('opsToken'), opsOut = byId('opsOut');",
  "try { tokenInput.value = sessionStorage.getItem(TOKEN_KEY) || ''; } catch (err) { /* none */ }",
  "tokenInput.addEventListener('input', function () {",
  "  try { sessionStorage.setItem(TOKEN_KEY, tokenInput.value); } catch (err) { /* none */ }",
  "});",
  "var OPS_ROUTES = {",
  "  reset: '/ops/reset',",
  "  stage: '/ops/stage-incident?region=riyadh-north',",
  "  ack: '/ops/ack?region=riyadh-north',",
  "  resolve: '/ops/resolve?region=riyadh-north',",
  "};",
  "Array.prototype.forEach.call(document.querySelectorAll('[data-op]'), function (btn) {",
  "  btn.addEventListener('click', function () {",
  "    var path = OPS_ROUTES[btn.getAttribute('data-op')];",
  "    if (!path) return;",
  "    opsOut.textContent = 'POST ' + path + ' …';",
  "    fetch(path, { method: 'POST', headers: {",
  "      authorization: 'Bearer ' + (tokenInput.value || '') } })",
  "      .then(function (res) {",
  "        return res.text().then(function (body) {",
  "          opsOut.textContent = res.status + ' ' + body;",
  "        });",
  "      })",
  "      .catch(function (err) { opsOut.textContent = 'failed: ' + err.message; });",
  "  });",
  "});",
  "})();",
].join("\n");

function bodyMarkup(cards: string): string {
  return [
  "<telnyx-ai-agent agent-id=\"" + DEMO_AGENT_ID + "\"></telnyx-ai-agent>",
  "<header class=\"top\">",
  "<div class=\"brand\"><strong class=\"mark\">NOC FRONT DOOR</strong>",
  "<span class=\"sub\">Najd Networks · 24/7 AI fault line</span></div>",
  "<div class=\"topRight\">",
  "<span class=\"live\"><span class=\"liveDot\"></span>LIVE</span>",
  "<span class=\"clock\" id=\"clock\">--:--:--</span>",
  "<span class=\"modeChip mono\" id=\"modeChip\">actors: …</span>",
  "</div>",
  "</header>",
  "<main class=\"wrap\">",
  "<section class=\"panel left\">",
  "<h2>Talk to Sanad</h2>",
  "<div class=\"orbWrap\">",
  "<button type=\"button\" class=\"orb\" id=\"orb\" aria-label=\"Start a call with Sanad\">",
  "<span class=\"ring r1\"></span><span class=\"ring r2\"></span><span class=\"ring r3\"></span>",
  ORB_SVG,
  "</button>",
  "</div>",
  "<p class=\"orbCap\" id=\"orbCap\">Tap the orb — or 'Talk to Sanad' bottom-right — and allow your microphone</p>",
  "<div class=\"cards\">" + cards + "</div>",
  "<div class=\"ribbon\">",
  "<p class=\"ribbonTitle\">How it works</p>",
  flowList(),
  "</div>",
  "</section>",
  "<section class=\"panel right\">",
  "<div class=\"boardHead\">",
  "<h2>NOC board</h2>",
  "<span class=\"stale\" id=\"staleBadge\" hidden>stale</span>",
  "</div>",
  "<div class=\"kpis\">",
  "<div class=\"kpi\"><span class=\"kLabel\">Open incidents</span><span class=\"kNum\" id=\"kInc\">–</span></div>",
  "<div class=\"kpi\"><span class=\"kLabel\">P1 incidents</span><span class=\"kNum\" id=\"kP1\">–</span></div>",
  "<div class=\"kpi\"><span class=\"kLabel\">Open tickets</span><span class=\"kNum\" id=\"kTix\">–</span></div>",
  "<div class=\"kpi\"><span class=\"kLabel\">Board age</span><span class=\"kNum\" id=\"kAge\">–</span></div>",
  "</div>",
  "<div class=\"regions\" id=\"regions\"></div>",
  "<h3>Event feed</h3>",
  "<ul class=\"feed\" id=\"feed\"></ul>",
  "<p class=\"panelFoot\">Live from Stateful Actors via /ops/board · refresh 5 s · data masked</p>",
  "</section>",
  "</main>",
  "<details class=\"drawer\" id=\"opsDrawer\">",
  "<summary>Operator</summary>",
  "<div class=\"drawerBody\">",
  "<label>OPS token<input type=\"password\" id=\"opsToken\" autocomplete=\"off\"></label>",
  "<div class=\"opsBtns\">",
  "<button type=\"button\" data-op=\"reset\">Reset demo</button>",
  "<button type=\"button\" data-op=\"stage\">Stage Riyadh North incident</button>",
  "<button type=\"button\" data-op=\"ack\">Acknowledge</button>",
  "<button type=\"button\" data-op=\"resolve\">Resolve</button>",
  "</div>",
  "<pre class=\"opsOut\" id=\"opsOut\"></pre>",
  "</div>",
  "</details>",
  "<footer class=\"foot\">",
  "<p>Built on Telnyx Voice AI · Edge Compute · KV · Stateful Actors · MCP — code authored by OpenCode on Telnyx Inference</p>",
  "<p>Calls are recorded and handled by an AI assistant.</p>",
  "</footer>",
  ].join("\n");
}

function pinChip(scenario: GuideScenario | undefined): string {
  if (scenario === undefined) {
    return `<span class="pin-miss">${GUIDE_FALLBACK}</span>`;
  }
  return `<button type="button" class="pin-chip" data-pin="${scenario.pin}">PIN ${scenario.pin} · click to copy</button>`;
}

function scenarioCard(
  num: number,
  title: string,
  say: string,
  watch: string,
  chip: string,
): string {
  const parts = [
    `<article class="card">`,
    `<span class="cardNum">${num}</span>`,
    `<h3>${title}</h3>`,
    `<p class="say">Say: <q>${say}</q></p>`,
    `<p class="watch">Watch: ${watch}</p>`,
  ];
  if (chip.length > 0) parts.push(chip);
  parts.push(`</article>`);
  return parts.join("");
}

export function renderDemoPage(guide: DemoGuide | null): string {
  const byKey = new Map<string, GuideScenario>();
  for (const scenario of guide?.scenarios ?? []) byKey.set(scenario.key, scenario);
  const cards = [
    scenarioCard(
      1,
      "Join the incident",
      "We are fully offline at the Al Yasmin branch in Riyadh North — site R U H one one four. I need to report an outage and join the ongoing incident.",
      "the Riyadh North incident turn P1 at 3 branches.",
      pinChip(byKey.get("join")),
    ),
    scenarioCard(
      2,
      "Open a new ticket",
      "Site J E D zero zero seven in Jeddah is down — phones and internet are offline. Please open a ticket for us.",
      "a new ticket appear under the Jeddah region.",
      pinChip(byKey.get("new")),
    ),
    scenarioCard(
      3,
      "Lockout &amp; human",
      "My PIN is not working — try a wrong PIN three times to hear the lock, then ask for a human engineer.",
      "Sanad lock the site after three wrong PINs, then page the on-call engineer.",
      "",
    ),
  ].join("");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>NOC Front Door — Live NOC wall</title>
<style>
${CSS}
</style>
</head>
<body>
${bodyMarkup(cards)}
<script async src="${WIDGET_SCRIPT_URL}"></script>
<script>
${APP_JS}
</script>
</body>
</html>
`;
}
