import type { DemoGuide, GuideScenario } from "./guide";

export const DEMO_AGENT_ID = "assistant-a2d301b3-f112-48f6-84c8-9e4d052cf3b7";

const WIDGET_SCRIPT_URL = "https://unpkg.com/@telnyx/ai-agent-widget@0.36.0";
const GUIDE_FALLBACK = "PIN: see the README reviewer guide";

// Cinematic "Live NOC wall". All dynamic board values go through
// createElement/textContent in the client script; the markup below is static.

const CSS_TOKENS = [
  ":root{color-scheme:dark;",
  "--bg:rgb(5,8,13);--surface:rgba(13,19,28,.66);--line:rgba(148,163,184,.14);",
  "--text:rgb(230,237,243);--muted:rgb(139,152,165);--dim:rgb(91,107,123);",
  "--accent:rgb(34,211,238);--indigo:rgb(99,102,241);--ok:rgb(52,211,153);",
  "--p2:rgb(245,158,11);--p1:rgb(244,63,94);--quiet:rgb(71,85,105);",
  "--glow:rgb(159,216,230);--radius:16px}",
  "*,*::before,*::after{box-sizing:border-box}",
  "html{background:var(--bg)}",
  "body{margin:0;min-height:100vh;background:var(--bg);color:var(--text);overflow-x:hidden;",
  "font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;line-height:1.55}",
  ".fx,.fxGrid,.fxNoise{position:fixed;inset:0;pointer-events:none;z-index:0}",
  ".fx .g{position:absolute;border-radius:50%;filter:blur(90px);opacity:.5}",
  ".fx .g1{width:34rem;height:34rem;left:-8rem;top:-10rem;",
  "background:radial-gradient(circle,rgba(34,211,238,.16),transparent 65%);",
  "animation:driftA 26s ease-in-out infinite alternate}",
  ".fx .g2{width:38rem;height:38rem;right:-10rem;bottom:-12rem;",
  "background:radial-gradient(circle,rgba(99,102,241,.18),transparent 65%);",
  "animation:driftB 32s ease-in-out infinite alternate}",
  ".fx .g3{width:24rem;height:24rem;left:38%;top:55%;",
  "background:radial-gradient(circle,rgba(52,211,153,.09),transparent 65%);",
  "animation:driftC 38s ease-in-out infinite alternate}",
  ".fxGrid{left:-25%;right:-25%;top:-5%;height:75%;",
  "background-image:linear-gradient(rgba(148,163,184,.055) 1px,transparent 1px),",
  "linear-gradient(90deg,rgba(148,163,184,.055) 1px,transparent 1px);",
  "background-size:44px 44px;transform:perspective(50rem) rotateX(38deg);",
  "transform-origin:top center;",
  "-webkit-mask-image:linear-gradient(180deg,rgba(0,0,0,.8),transparent 88%);",
  "mask-image:linear-gradient(180deg,rgba(0,0,0,.8),transparent 88%)}",
  ".fxNoise{opacity:.05;mix-blend-mode:overlay;",
  // The noise tile is an inline SVG filter; the xmlns digits are
  // percent-encoded so no 4-digit run ever appears in this document.
  "background-image:url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/20%30%30/svg' width='260' height='260'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.85' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='260' height='260' filter='url(%23n)' opacity='.5'/%3E%3C/svg%3E\")}",
  ".mono,.kNum,.kSub,.clock,.cardNum,.ftime,.mlab,.pin-chip{",
  "font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;",
  "font-variant-numeric:tabular-nums}",
  "h1,h2,h3{margin:0;font-weight:650;letter-spacing:-.01em}",
  "h2{font-size:1.02rem;color:var(--muted);text-transform:uppercase;letter-spacing:.14em}",
  "h3{font-size:1rem}",
  "p{margin:.5rem 0}",
  "main{position:relative;z-index:1}",
].join("\n");
const CSS_HEADER = [
  ".top{position:sticky;top:0;z-index:20;display:flex;align-items:center;",
  "justify-content:space-between;gap:1rem;padding:.85rem 1.5rem;",
  "border-bottom:1px solid var(--line);background:rgba(5,8,13,.72);",
  "backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px)}",
  ".brand{display:flex;flex-direction:column;gap:.1rem}",
  ".mark{font-size:1.02rem;font-weight:800;letter-spacing:.22em;",
  "background:linear-gradient(92deg,var(--text) 25%,var(--glow) 55%,rgba(99,102,241,.95));",
  "-webkit-background-clip:text;background-clip:text;color:transparent}",
  ".sub{font-size:.72rem;color:var(--dim);letter-spacing:.06em}",
  ".topRight{display:flex;align-items:center;gap:.7rem;flex-wrap:wrap}",
  ".live{display:inline-flex;align-items:center;gap:.42rem;color:var(--ok)",
  ";border:1px solid rgba(52,211,153,.35);background:rgba(52,211,153,.06);",
  "border-radius:999px;padding:.18rem .68rem;font-size:.72rem;font-weight:700;",
  "letter-spacing:.16em}",
  ".liveDot{width:8px;height:8px;border-radius:50%;background:var(--ok);",
  "box-shadow:0 0 8px rgba(52,211,153,.9);animation:breathe 2.2s ease-in-out infinite}",
  ".clock{color:var(--muted);font-size:.86rem;letter-spacing:.04em}",
  ".modeChip{border:1px solid var(--line);color:var(--muted);border-radius:999px;",
  "padding:.18rem .6rem;font-size:.72rem}",
  ".hair{position:absolute;left:0;bottom:-1px;height:2px;width:100%;opacity:0;",
  "transform:scaleX(0);transform-origin:left;",
  "background:linear-gradient(90deg,var(--accent),rgba(99,102,241,.85),transparent)}",
  ".hair.run{animation:hairline .9s ease-out}",
].join("\n");
const CSS_LAYOUT = [
  ".wrap{max-width:85rem;margin:0 auto;padding:1.5rem;display:grid;gap:1.25rem;",
  "grid-template-columns:1fr}",
  "@media (min-width:68.75em){.wrap{grid-template-columns:5fr 7fr;align-items:start}}",
  ".panel{position:relative;background:var(--surface);",
  "backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);",
  "border-radius:var(--radius);padding:1.15rem 1.25rem 1.3rem;",
  "box-shadow:0 18px 48px rgba(2,6,12,.55),inset 0 1px 0 rgba(255,255,255,.05)}",
  // 1px luminous gradient border: the pseudo-element's gradient is masked
  // down to its own padding ring, leaving exactly one pixel visible.
  ".panel::before{content:'';position:absolute;inset:0;border-radius:inherit;",
  "padding:1px;pointer-events:none;",
  "background:linear-gradient(160deg,rgba(34,211,238,.32),rgba(99,102,241,.14) 38%,",
  "rgba(148,163,184,.07) 70%);",
  "-webkit-mask:linear-gradient(#fff 0 0) content-box,linear-gradient(#fff 0 0);",
  "-webkit-mask-composite:xor;",
  "mask:linear-gradient(#fff 0 0) content-box,linear-gradient(#fff 0 0);",
  "mask-composite:exclude}",
  ".panel>h2{display:flex;align-items:center;gap:.6rem;margin-bottom:.9rem}",
].join("\n");
const CSS_ORB = [
  ".orbWrap{display:flex;justify-content:center;padding:1.2rem 0 .4rem}",
  ".orb{position:relative;width:9.5rem;height:9.5rem;border-radius:50%;border:none;",
  "cursor:pointer;display:flex;align-items:center;justify-content:center;gap:4px;",
  "color:var(--accent);",
  "background:radial-gradient(circle at 50% 38%,rgba(34,211,238,.3),",
  "rgba(99,102,241,.12) 55%,transparent 72%);",
  "transition:transform .25s ease,box-shadow .25s ease}",
  ".orb:hover{transform:scale(1.05);box-shadow:0 0 46px rgba(34,211,238,.32)}",
  ".orb:focus-visible{outline:2px solid var(--accent);outline-offset:5px}",
  // Rotating conic sweep, masked into a thin ring.
  ".orbConic{position:absolute;inset:-7px;border-radius:50%;pointer-events:none;",
  "background:conic-gradient(from 0deg,rgba(34,211,238,0) 0deg,rgba(34,211,238,.9) 55deg,",
  "rgba(99,102,241,.75) 120deg,rgba(34,211,238,0) 175deg,rgba(34,211,238,0) 360deg);",
  "animation:spin 4.2s linear infinite;",
  "-webkit-mask:radial-gradient(farthest-side,transparent calc(100% - 6px),#000 calc(100% - 5px));",
  "mask:radial-gradient(farthest-side,transparent calc(100% - 6px),#000 calc(100% - 5px))}",
  ".pulse{position:absolute;inset:0;border-radius:50%;border:1px solid rgba(34,211,238,.5);",
  "animation:pulseOut 2.8s ease-out infinite;opacity:0;pointer-events:none}",
  ".pulse.p2b{animation-delay:1.4s}",
  ".bar{width:4px;border-radius:2px;transform-origin:center;",
  "background:linear-gradient(180deg,var(--accent),rgba(99,102,241,.85));",
  "box-shadow:0 0 8px rgba(34,211,238,.55);animation:wave 1.15s ease-in-out infinite}",
  ".bar.b1,.bar.b7{height:12px}.bar.b2,.bar.b6{height:20px}",
  ".bar.b3,.bar.b5{height:27px}.bar.b4{height:34px}",
  ".bar.b2{animation-delay:.12s}.bar.b3{animation-delay:.24s}",
  ".bar.b4{animation-delay:.36s}.bar.b5{animation-delay:.48s}",
  ".bar.b6{animation-delay:.6s}.bar.b7{animation-delay:.72s}",
  ".orbCap{text-align:center;color:var(--muted);font-size:.9rem;",
  "margin:.95rem 0 0;min-height:1.5em}",
  ".orbCap.connecting{color:var(--accent)}",
  ".orbHint{text-align:center;color:var(--dim);font-size:.76rem;margin:.15rem 0 0}",
  ".cards{display:flex;flex-direction:column;gap:.95rem;margin-top:1.15rem}",
  ".card{position:relative;border:1px solid var(--line);border-radius:12px;",
  "padding:.9rem 1rem;background:rgba(9,14,21,.6);",
  "box-shadow:inset 0 1px 0 rgba(255,255,255,.04);",
  "transition:border-color .25s ease,box-shadow .25s ease}",
  ".card:hover{border-color:rgba(34,211,238,.35);",
  "box-shadow:0 0 1.2rem rgba(34,211,238,.1),inset 0 1px 0 rgba(255,255,255,.05)}",
  ".cardNum{position:absolute;top:-.6rem;left:.9rem;border-radius:8px;",
  "padding:.06rem .5rem;font-size:.76rem;font-weight:800;color:rgb(3,18,24);",
  "background:linear-gradient(120deg,var(--accent),rgb(125,211,252))}",
  ".card h3{margin:.35rem 0 .3rem;font-size:.98rem}",
  ".say{font-size:.88rem}",
  ".say q{color:var(--glow)}",
  ".watch{font-size:.8rem;color:var(--dim)}",
  ".pin-chip{margin-top:.55rem;border:1px dashed rgba(34,211,238,.5);",
  "color:var(--accent);background:rgba(34,211,238,.08);border-radius:999px;",
  "padding:.3rem .75rem;cursor:pointer;font-size:.8rem;",
  "transition:background .2s ease,box-shadow .2s ease}",
  ".pin-chip:hover{background:rgba(34,211,238,.16);",
  "box-shadow:0 0 12px rgba(34,211,238,.25)}",
  ".pin-chip.copied{color:var(--ok);border-color:rgba(52,211,153,.6);",
  "background:rgba(52,211,153,.1)}",
  ".pin-miss{display:inline-block;margin-top:.55rem;color:var(--dim);",
  "font-size:.8rem;border:1px dashed rgba(139,152,165,.35);",
  "border-radius:999px;padding:.3rem .75rem}",
].join("\n");
const CSS_RIBBON = [
  ".ribbon{margin-top:1.5rem;border-top:1px solid var(--line);padding-top:1.05rem}",
  ".ribbonTitle{font-size:.72rem;color:var(--dim);text-transform:uppercase;",
  "letter-spacing:.16em;margin:0 0 .85rem}",
  ".flow{list-style:none;display:flex;gap:.4rem;margin:0;padding:0;flex-wrap:wrap;",
  "align-items:stretch;justify-content:space-between}",
  ".flow li{flex:1 1 0;min-width:6.6rem;position:relative;text-align:center;",
  "font-size:.72rem;color:var(--muted);display:flex;flex-direction:column;",
  "align-items:center;gap:.35rem;padding:.4rem .25rem .35rem;",
  "border:1px solid rgba(148,163,184,.08);border-radius:10px;",
  "background:rgba(9,14,21,.45)}",
  ".flow li:not(:last-child)::before{content:'';position:absolute;top:1.28rem;",
  "left:calc(50% + 1.55rem);right:calc(-50% + 1.55rem);height:1px;",
  "background:linear-gradient(90deg,rgba(34,211,238,.5),rgba(99,102,241,.4))}",
  // the travelling light pulse riding each connector line
  ".flow li:not(:last-child)::after{content:'';position:absolute;top:1.21rem;",
  "left:calc(50% + 1.55rem);width:5px;height:5px;border-radius:50%;",
  "background:var(--accent);",
  "box-shadow:0 0 8px rgba(34,211,238,.95),0 0 16px rgba(34,211,238,.5);",
  "animation:flowDot 3s linear infinite}",
  ".flow li:nth-child(2)::after{animation-delay:.75s}",
  ".flow li:nth-child(3)::after{animation-delay:1.5s}",
  ".flow li:nth-child(4)::after{animation-delay:2.25s}",
  ".flow svg{width:1.45rem;height:1.45rem;color:var(--accent);",
  "filter:drop-shadow(0 0 5px rgba(34,211,238,.5))}",
  ".flow small{display:block;color:var(--dim);font-size:.64rem}",
].join("\n");
const CSS_MAP = [
  ".mapPanel{margin:1.05rem 0 1rem;border:1px solid var(--line);border-radius:12px;",
  "background:rgba(9,14,21,.55);padding:.7rem .8rem .55rem}",
  ".mapHead{display:flex;justify-content:space-between;align-items:baseline;",
  "margin-bottom:.4rem}",
  ".mapTitle{font-size:.66rem;color:var(--dim);text-transform:uppercase;",
  "letter-spacing:.16em}",
  ".mapHint{font-size:.6rem;color:rgba(52,211,153,.8);letter-spacing:.14em;",
  "text-transform:uppercase}",
  ".map{display:block;width:100%;height:auto;border-radius:8px}",
  ".mapDots{fill:url(#dots)}",
  ".land{fill:rgba(30,41,59,.55);stroke:rgba(148,163,184,.28);stroke-width:1;",
  "filter:drop-shadow(0 0 14px rgba(34,211,238,.07))}",
  "#dots circle{fill:rgba(148,163,184,.16)}",
  ".mdot{fill:var(--quiet);transition:fill .3s ease}",
  ".mring{fill:none;stroke:rgba(34,211,238,.55);stroke-width:1;opacity:0;",
  "transform-box:fill-box;transform-origin:center}",
  ".mping{fill:none;stroke:var(--p1);stroke-width:1.6;opacity:0;",
  "transform-box:fill-box;transform-origin:center}",
  ".mlab{opacity:0;font-size:9px;fill:rgb(251,113,133);text-anchor:middle;",
  "letter-spacing:.06em}",
  ".state-tix .mdot{fill:var(--accent);",
  "filter:drop-shadow(0 0 4px rgba(34,211,238,.8))}",
  ".state-tix .mring{opacity:1;animation:ringBreathe 2.6s ease-in-out infinite}",
  ".state-p2 .mdot{fill:var(--p2);",
  "filter:drop-shadow(0 0 5px rgba(245,158,11,.85))}",
  ".state-p2 .mring{stroke:rgba(245,158,11,.6);opacity:1;",
  "animation:ringBreathe 2.1s ease-in-out infinite}",
  ".state-p1 .mdot{fill:var(--p1);",
  "filter:drop-shadow(0 0 6px rgba(244,63,94,.9))}",
  ".state-p1 .mping{opacity:1;animation:radar 1.7s ease-out infinite}",
  ".state-p1 .mlab{opacity:1}",
].join("\n");
const CSS_BOARD = [
  ".boardHead{display:flex;align-items:center;gap:.6rem}",
  ".stale{border:1px solid rgba(245,158,11,.55);color:var(--p2);",
  "border-radius:999px;padding:.14rem .55rem;font-size:.68rem;font-weight:700;",
  "letter-spacing:.1em;text-transform:uppercase}",
  ".kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:.7rem;margin:.4rem 0 0}",
  "@media (max-width:40em){.kpis{grid-template-columns:repeat(2,1fr)}}",
  ".kpi{border:1px solid var(--line);border-radius:12px;padding:.6rem .75rem .55rem;",
  "background:rgba(9,14,21,.55);box-shadow:inset 0 1px 0 rgba(255,255,255,.04)}",
  ".kLabel{display:block;font-size:.62rem;color:var(--dim);text-transform:uppercase;",
  "letter-spacing:.12em;white-space:nowrap}",
  ".kNum{display:block;font-size:1.5rem;line-height:1.2;color:var(--text);",
  "margin-top:.15rem;white-space:nowrap}",
  ".kSub{display:block;font-size:.62rem;color:var(--dim);letter-spacing:.06em;",
  "white-space:nowrap}",
  ".kpi.hot .kNum{color:var(--p1);text-shadow:0 0 12px rgba(244,63,94,.45)}",
  ".regions{display:grid;grid-template-columns:repeat(2,1fr);gap:.8rem}",
  "@media (max-width:40em){.regions{grid-template-columns:1fr}}",
  ".regionCard{border:1px solid var(--line);border-radius:12px;padding:.75rem .85rem;",
  "background:rgba(9,14,21,.55);box-shadow:inset 0 1px 0 rgba(255,255,255,.04);",
  "transition:border-color .3s ease,box-shadow .3s ease}",
  ".regionCard.quiet{border-color:rgba(71,85,105,.55);color:var(--dim)}",
  ".regionCard.tix{border-color:rgba(34,211,238,.4)}",
  ".regionCard.p2{border-color:rgba(245,158,11,.55);",
  "box-shadow:0 0 1rem rgba(245,158,11,.08),inset 0 1px 0 rgba(255,255,255,.04)}",
  ".regionCard.p1{border-color:rgba(244,63,94,.6);animation:p1Glow 3.2s ease-in-out infinite}",
  ".regionCard.upgraded{animation:borderFlash 1.6s ease-out}",
  ".regionCard.flash{animation:rowFlash 1.2s ease-out}",
  ".regionHead{display:flex;justify-content:space-between;align-items:center;gap:.5rem}",
  ".regionName{font-size:.9rem;font-weight:650}",
  ".chip{font-size:.6rem;font-weight:800;letter-spacing:.14em;border-radius:6px;",
  "padding:.16rem .5rem;border:1px solid var(--line);color:var(--dim);",
  "text-transform:uppercase}",
  ".regionCard.tix .chip{color:var(--accent);border-color:rgba(34,211,238,.55);",
  "box-shadow:0 0 8px rgba(34,211,238,.2)}",
  ".regionCard.p2 .chip{color:var(--p2);border-color:rgba(245,158,11,.6);",
  "box-shadow:0 0 8px rgba(245,158,11,.22)}",
  ".regionCard.p1 .chip{color:var(--p1);border-color:rgba(244,63,94,.65);",
  "box-shadow:0 0 10px rgba(244,63,94,.3)}",
  ".incLine{margin:.45rem 0 .1rem;font-size:.76rem;color:var(--muted)}",
  ".incLine .mono{color:var(--text)}",
  ".tixList{display:flex;flex-direction:column;gap:.35rem;margin-top:.5rem}",
  ".tixRow{display:flex;align-items:center;gap:.45rem;flex-wrap:wrap;",
  "border:1px solid rgba(148,163,184,.1);border-radius:9px;padding:.28rem .5rem;",
  "background:rgba(15,22,31,.55);font-size:.72rem;color:var(--muted)}",
  ".tixRow.flash{animation:rowFlash 1.2s ease-out}",
  ".tixRow .tid{color:var(--text)}",
  ".tixRow .tlabel{flex:1 1 auto;min-width:5rem}",
  ".prio{display:inline-block;border-radius:5px;padding:.03rem .36rem;",
  "font-size:.62rem;font-weight:800;letter-spacing:.08em}",
  ".prio.P1{color:var(--p1);border:1px solid rgba(244,63,94,.55)}",
  ".prio.P2{color:var(--p2);border:1px solid rgba(245,158,11,.55)}",
  ".ttime{color:var(--dim);font-size:.64rem}",
  ".panelFoot{margin:1.05rem 0 0;font-size:.7rem;color:var(--dim)}",
].join("\n");
const CSS_FEED = [
  ".feedTitle{margin-top:1.1rem}",
  ".feed{list-style:none;margin:.5rem 0 0;padding:0;position:relative}",
  ".feed::before{content:'';position:absolute;left:5px;top:8px;bottom:8px;width:1px;",
  "background:linear-gradient(180deg,rgba(34,211,238,.4),rgba(99,102,241,.18))}",
  ".feed li{position:relative;padding:.3rem .4rem .3rem 1.25rem;font-size:.76rem;",
  "color:var(--muted)}",
  ".feed li::before{content:'';position:absolute;left:2px;top:.72em;width:7px;",
  "height:7px;border-radius:50%;background:var(--quiet)}",
  ".feed li.k-accent::before{background:var(--accent);",
  "box-shadow:0 0 7px rgba(34,211,238,.85)}",
  ".feed li.k-warn::before{background:var(--p2);box-shadow:0 0 7px rgba(245,158,11,.85)}",
  ".feed li.k-crit::before{background:var(--p1);box-shadow:0 0 7px rgba(244,63,94,.9)}",
  ".feed li.k-ok::before{background:var(--ok);box-shadow:0 0 7px rgba(52,211,153,.85)}",
  ".feed li.fresh{animation:fadeIn .9s ease-out}",
  ".feed .ftime{float:right;color:var(--dim);font-size:.64rem;padding-left:.6rem}",
  ".feed .ftext{margin-right:.5rem}",
  ".drawer{position:relative;z-index:10;max-width:85rem;margin:0 auto 2rem;",
  "padding:0 1.5rem}",
  ".drawer summary{cursor:pointer;color:var(--dim);font-size:.8rem;width:max-content}",
  ".drawerBody{border:1px solid var(--line);border-radius:var(--radius);",
  "margin-top:.6rem;padding:1rem 1.1rem;background:var(--surface);",
  "backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);",
  "display:flex;flex-direction:column;gap:.8rem}",
  ".drawerBody label{font-size:.8rem;color:var(--muted);display:flex;",
  "flex-direction:column;gap:.3rem}",
  ".drawerBody input{background:rgba(5,8,13,.85);border:1px solid var(--line);",
  "color:var(--text);border-radius:8px;padding:.45rem .6rem;font-size:.86rem;",
  "width:min(22rem,100%)}",
  ".opsBtns{display:flex;gap:.6rem;flex-wrap:wrap}",
  ".opsBtns button{border:1px solid rgba(34,211,238,.4);color:var(--accent);",
  "background:rgba(34,211,238,.07);border-radius:10px;padding:.42rem .8rem;",
  "font-size:.8rem;cursor:pointer;transition:background .2s ease}",
  ".opsBtns button:hover{background:rgba(34,211,238,.16)}",
  ".opsOut{margin:0;font-size:.74rem;color:var(--muted);white-space:pre-wrap;",
  "word-break:break-word;min-height:1.4em}",
  ".foot{position:relative;z-index:1;max-width:85rem;margin:0 auto;",
  "padding:0 1.5rem 2.2rem;color:var(--dim);font-size:.76rem;text-align:center}",
].join("\n");
const CSS_ANIMS = [
  "@keyframes driftA{0%{transform:translate(0,0)}100%{transform:translate(6rem,3rem)}}",
  "@keyframes driftB{0%{transform:translate(0,0)}100%{transform:translate(-5rem,-4rem)}}",
  "@keyframes driftC{0%{transform:translate(0,0) scale(1)}",
  "100%{transform:translate(-4rem,3rem) scale(1.15)}}",
  "@keyframes breathe{0%,100%{transform:scale(1);opacity:1}",
  "50%{transform:scale(1.4);opacity:.55}}",
  "@keyframes hairline{0%{transform:scaleX(0);opacity:1}",
  "100%{transform:scaleX(1);opacity:0}}",
  "@keyframes spin{to{transform:rotate(1turn)}}",
  "@keyframes pulseOut{0%{transform:scale(.82);opacity:.85}",
  "100%{transform:scale(1.45);opacity:0}}",
  "@keyframes wave{0%,100%{transform:scaleY(.4)}50%{transform:scaleY(1)}}",
  "@keyframes flowDot{0%{left:calc(50% + 1.55rem);opacity:0}12%{opacity:1}",
  "88%{opacity:1}100%{left:calc(100% - 1.55rem);opacity:0}}",
  "@keyframes ringBreathe{0%,100%{transform:scale(1);opacity:.9}",
  "50%{transform:scale(1.45);opacity:.3}}",
  "@keyframes radar{0%{transform:scale(.55);opacity:.95}",
  "100%{transform:scale(2.6);opacity:0}}",
  "@keyframes p1Glow{0%,100%{box-shadow:0 0 .4rem 0 rgba(244,63,94,.05),",
  "inset 0 1px 0 rgba(255,255,255,.04)}",
  "50%{box-shadow:0 0 1.6rem .1rem rgba(244,63,94,.28),",
  "inset 0 1px 0 rgba(255,255,255,.05)}}",
  "@keyframes borderFlash{0%{box-shadow:0 0 0 .05rem rgba(244,63,94,.6);",
  "border-color:rgb(244,63,94)}100%{box-shadow:0 0 0 0 rgba(244,63,94,0)}}",
  "@keyframes rowFlash{0%{box-shadow:0 0 0 .15rem rgba(34,211,238,.5);",
  "border-color:rgb(34,211,238)}100%{box-shadow:0 0 0 0 rgba(34,211,238,0)}}",
  "@keyframes fadeIn{0%{opacity:0;transform:translateY(-.35rem)}",
  "100%{opacity:1;transform:none}}",
  "@media (prefers-reduced-motion: reduce){",
  "*,*::before,*::after{animation:none !important;transition:none !important}}",
].join("\n");

const CSS = [
  CSS_TOKENS,
  CSS_HEADER,
  CSS_LAYOUT,
  CSS_ORB,
  CSS_RIBBON,
  CSS_MAP,
  CSS_BOARD,
  CSS_FEED,
  CSS_ANIMS,
].join("\n");

const FLOW_SVGS = [
  "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7' aria-hidden='true'><circle cx='12' cy='8' r='3.4'/><path d='M5 20a7 7 0 0 1 14 0'/></svg>",
  "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7' stroke-linecap='round' aria-hidden='true'><path d='M3 12h3l2-6 3 12 3-9 2 3h4'/></svg>",
  "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7' stroke-linecap='round' aria-hidden='true'><rect x='4' y='4' width='16' height='16' rx='3'/><path d='M9 9h6M9 13h6M9 17h3'/></svg>",
  "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7' stroke-linecap='round' aria-hidden='true'><ellipse cx='12' cy='6' rx='7' ry='3'/><path d='M5 6v12c0 1.7 3.1 3 7 3s7-1.3 7-3V6'/><path d='M5 12c0 1.7 3.1 3 7 3s7-1.3 7-3'/></svg>",
  "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.7' stroke-linecap='round' aria-hidden='true'><rect x='3' y='5' width='18' height='12' rx='2'/><path d='M8 21h8M12 17v4'/></svg>",
];

const FLOW_STEPS = [
  "Caller",
  "Telnyx Voice AI<small>Sanad · workflow</small>",
  "Edge Function<small>dynamic variables · tools · MCP</small>",
  "Stateful Actors + KV",
  "NOC board",
];

function flowList(): string {
  const items = FLOW_STEPS.map(
    (step, i) => `<li>${FLOW_SVGS[i]}<span>${step}</span></li>`,
  );
  return `<ol class="flow">${items.join("")}</ol>`;
}

// Abstract KSA situation map: a soft rounded landmass on a dotted grid, no
// attempt at a real coastline. Markers are labelled by region id so the
// client script can restyle them per board state.
const MAP_MARKERS: ReadonlyArray<readonly [string, number, number]> = [
  ["jeddah", 86, 138],
  ["riyadh-north", 196, 106],
  ["riyadh-south", 205, 149],
  ["dammam", 283, 90],
];

function mapSvg(): string {
  const markers = MAP_MARKERS.map(
    ([region, x, y]) =>
      `<g class="mmark state-quiet" id="map-${region}" transform="translate(${x},${y})">` +
      `<circle class="mping" r="7"></circle>` +
      `<circle class="mring" r="11"></circle>` +
      `<circle class="mdot" r="4.5"></circle>` +
      `<text class="mlab" y="-14"></text></g>`,
  ).join("");
  return [
    `<svg id="ksaMap" class="map" viewBox="0 0 360 250" role="img"`,
    ` aria-label="Stylised situation map of Saudi Arabia">`,
    `<defs><pattern id="dots" width="16" height="16" patternUnits="userSpaceOnUse">`,
    `<circle cx="2" cy="2" r=".9"></circle></pattern></defs>`,
    `<rect class="mapDots" width="360" height="250"></rect>`,
    `<path class="land" d="M54,64 Q98,30 178,40 L290,56 Q324,62 320,104 `,
    `L310,182 Q304,220 250,216 L98,208 Q46,203 48,156 Z"></path>`,
    markers,
    `</svg>`,
  ].join("");
}

const JS_CORE = [
  "(function () {",
  "'use strict';",
  "var POLL_MS = 5e3, FETCH_MS = 8e3, FLASH_MS = 12e2, CLOCK_MS = 1e3;",
  "var board = null, prevByRegion = {}, prioByRegion = {}, tixBySite = {},",
  "  generatedMs = 0;",
  "var feedItems = [];",
  "function el(tag, cls, text) {",
  "  var node = document.createElement(tag);",
  "  if (cls) node.className = cls;",
  "  if (text !== undefined && text !== null) node.textContent = String(text);",
  "  return node;",
  "}",
  "function byId(id) { return document.getElementById(id); }",
  "function rel(at) {",
  "  var s = Math.max(0, Math.round((Date.now() - at) / 1e3));",
  "  if (s >= 60) return Math.floor(s / 60) + 'm ago';",
  "  return s + 's ago';",
  "}",
  "/* header clock, board age tile and feed relative times tick every second */",
  "var clockEl = byId('clock');",
  "var riyadh = new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Riyadh',",
  "  hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false });",
  "function updateAge() {",
  "  if (board === null) return;",
  "  var ageS = Math.max(0, Math.round((Date.now() - generatedMs) / 1e3));",
  "  byId('kAge').textContent = ageS + ' s';",
  "}",
  "function updateFeedTimes() {",
  "  var times = document.querySelectorAll('.ftime');",
  "  for (var i = 0; i < times.length; i++) {",
  "    var at = Number(times[i].getAttribute('data-at') || 0);",
  "    if (at > 0) times[i].textContent = rel(at);",
  "  }",
  "}",
  "setInterval(function () {",
  "  if (clockEl) clockEl.textContent = riyadh.format(new Date());",
  "  updateAge();",
  "  updateFeedTimes();",
  "}, CLOCK_MS);",
  "if (clockEl) clockEl.textContent = riyadh.format(new Date());",
  "/* pin chips: click to copy */",
  "Array.prototype.forEach.call(document.querySelectorAll('.pin-chip'), function (chip) {",
  "  var pin = chip.getAttribute('data-pin') || '';",
  "  chip.addEventListener('click', function () {",
  "    var restore = function () {",
  "      chip.textContent = 'PIN ' + pin + ' · click to copy';",
  "      chip.classList.remove('copied');",
  "    };",
  "    var write = function () {",
  "      chip.textContent = 'copied ✓';",
  "      chip.classList.add('copied');",
  "      setTimeout(restore, FLASH_MS);",
  "    };",
  "    var fallback = function () {",
  "      var area = el('textarea');",
  "      area.value = pin;",
  "      area.setAttribute('readonly', '');",
  "      area.style.position = 'fixed';",
  "      area.style.opacity = '0';",
  "      document.body.appendChild(area);",
  "      area.select();",
  "      try { document.execCommand('copy'); } catch (err) { /* none */ }",
  "      document.body.removeChild(area);",
  "      write();",
  "    };",
  "    if (navigator.clipboard && navigator.clipboard.writeText) {",
  "      navigator.clipboard.writeText(pin).then(write, fallback);",
  "    } else { fallback(); }",
  "  });",
  "});",
  "/* the hero orb clicks the widget's own launcher inside its shadow root */",
  "var orb = byId('orb'), cap = byId('orbCap');",
  "orb.addEventListener('click', function () {",
  "  var host = document.querySelector('telnyx-ai-agent');",
  "  var launcher = host && host.shadowRoot ? host.shadowRoot.querySelector('button') : null;",
  "  if (launcher) launcher.click();",
  "  cap.classList.add('connecting');",
  "  cap.textContent = launcher",
  "    ? 'Connecting… allow your microphone, then speak to Sanad.'",
  "    : 'Connecting… the voice widget is still loading — one moment.';",
  "});",
].join("\n");
const JS_RENDER = [
  "/* board rendering: map markers, region cards, event feed */",
  "function regionTicketCount(next, regionId) {",
  "  var n = 0;",
  "  for (var i = 0; i < next.sites.length; i++) {",
  "    if (next.sites[i].region === regionId && next.sites[i].open_ticket !== null) n++;",
  "  }",
  "  return n;",
  "}",
  "function regionState(region, tix) {",
  "  if (region.incident !== null) {",
  "    return region.incident.priority === 'P1' ? 'p1' : 'p2';",
  "  }",
  "  return tix > 0 ? 'tix' : 'quiet';",
  "}",
  "function renderMap(next) {",
  "  for (var r = 0; r < next.regions.length; r++) {",
  "    var region = next.regions[r];",
  "    var g = byId('map-' + region.region);",
  "    if (!g) continue;",
  "    g.setAttribute('class',",
  "      'mmark state-' + regionState(region, regionTicketCount(next, region.region)));",
  "    var lab = g.querySelector('.mlab');",
  "    if (lab) lab.textContent = region.incident === null ? '' : region.incident.id;",
  "  }",
  "}",
  "function chipText(state) {",
  "  if (state === 'quiet') return 'QUIET';",
  "  if (state === 'tix') return 'TICKETS';",
  "  return state.toUpperCase();",
  "}",
  "function ticketRows(card, next, regionId, flashed) {",
  "  var list = el('div', 'tixList');",
  "  var used = false;",
  "  for (var i = 0; i < next.sites.length; i++) {",
  "    var site = next.sites[i];",
  "    if (site.region !== regionId || site.open_ticket === null) continue;",
  "    used = true;",
  "    var row = el('div', 'tixRow');",
  "    row.appendChild(el('span', 'mono tid', site.site_id));",
  "    row.appendChild(el('span', 'tlabel', site.label.replace(/^the /, '')));",
  "    row.appendChild(el('span', 'mono', site.open_ticket.id));",
  "    row.appendChild(",
  "      el('span', 'prio ' + site.open_ticket.priority, site.open_ticket.priority));",
  "    row.appendChild(el('span', 'mono ttime', site.open_ticket.opened_local));",
  "    var sig = site.open_ticket.id + ':' + site.open_ticket.priority;",
  "    if (tixBySite[site.site_id] !== undefined && tixBySite[site.site_id] !== sig) {",
  "      row.classList.add('flash');",
  "      flashed.push(row);",
  "    }",
  "    tixBySite[site.site_id] = sig;",
  "    list.appendChild(row);",
  "  }",
  "  if (used) card.appendChild(list);",
  "}",
  "function signature(region, sites) {",
  "  var parts = [region.label];",
  "  if (region.incident !== null) {",
  "    parts.push(region.incident.id, region.incident.priority,",
  "      String(region.incident.site_count), region.incident.declared_local);",
  "  } else { parts.push('-'); }",
  "  for (var i = 0; i < sites.length; i++) {",
  "    var site = sites[i];",
  "    if (site.region !== region.region || site.open_ticket === null) continue;",
  "    parts.push(site.site_id + ':' + site.open_ticket.id + ':' + site.open_ticket.priority);",
  "  }",
  "  return parts.join('|');",
  "}",
  "function renderRegions(next, prev) {",
  "  var host = byId('regions');",
  "  while (host.firstChild) host.removeChild(host.firstChild);",
  "  var flashed = [];",
  "  for (var r = 0; r < next.regions.length; r++) {",
  "    var region = next.regions[r];",
  "    var inc = region.incident;",
  "    var tix = regionTicketCount(next, region.region);",
  "    var state = regionState(region, tix);",
  "    var card = el('article', 'regionCard ' + state);",
  "    var head = el('div', 'regionHead');",
  "    head.appendChild(el('span', 'regionName', region.label));",
  "    head.appendChild(el('span', 'chip', chipText(state)));",
  "    card.appendChild(head);",
  "    if (inc !== null) {",
  "      var incLine = el('p', 'incLine');",
  "      incLine.appendChild(el('span', 'mono', inc.id));",
  "      incLine.appendChild(el('span', '', ' · ' + inc.site_count +",
  "        (inc.site_count === 1 ? ' branch' : ' branches') +",
  "        ' · declared ' + inc.declared_local));",
  "      card.appendChild(incLine);",
  "    } else {",
  "      card.appendChild(el('p', 'incLine', state === 'tix'",
  "        ? 'no incident · ' + tix + (tix === 1 ? ' ticket' : ' tickets') + ' open'",
  "        : 'all sites nominal'));",
  "    }",
  "    ticketRows(card, next, region.region, flashed);",
  "    var sig = signature(region, next.sites);",
  "    if (prev !== null && prevByRegion[region.region] !== undefined &&",
  "        prevByRegion[region.region] !== sig) {",
  "      card.classList.add('flash');",
  "      flashed.push(card);",
  "    }",
  "    var prevPrio = prioByRegion[region.region];",
  "    if (prevPrio === 'P2' && inc !== null && inc.priority === 'P1') {",
  "      card.classList.add('upgraded');",
  "    }",
  "    prioByRegion[region.region] = inc === null ? null : inc.priority;",
  "    prevByRegion[region.region] = sig;",
  "    host.appendChild(card);",
  "  }",
  "  setTimeout(function () {",
  "    for (var i = 0; i < flashed.length; i++) flashed[i].classList.remove('flash');",
  "  }, FLASH_MS);",
  "}",
  "/* event feed: client-side diff of consecutive board snapshots */",
  "function diffLines(prev, next) {",
  "  var lines = [];",
  "  for (var r = 0; r < next.regions.length; r++) {",
  "    var region = next.regions[r];",
  "    var before = null;",
  "    for (var q = 0; q < prev.regions.length; q++) {",
  "      if (prev.regions[q].region === region.region) { before = prev.regions[q]; break; }",
  "    }",
  "    var prevInc = before === null ? null : before.incident;",
  "    var inc = region.incident;",
  "    if (prevInc === null && inc !== null) {",
  "      lines.push(inc.id + ' declared ' + inc.priority + ' · ' + region.label);",
  "    }",
  "    if (prevInc !== null && inc === null) lines.push(prevInc.id + ' resolved');",
  "    if (prevInc !== null && inc !== null && prevInc.priority !== inc.priority) {",
  "      lines.push(inc.id + (inc.priority === 'P1'",
  "        ? ' raised to P1 · ' + inc.site_count + ' branches'",
  "        : ' lowered to ' + inc.priority));",
  "    }",
  "  }",
  "  for (var s = 0; s < next.sites.length; s++) {",
  "    var site = next.sites[s];",
  "    var prevSite = null;",
  "    for (var t = 0; t < prev.sites.length; t++) {",
  "      if (prev.sites[t].site_id === site.site_id) { prevSite = prev.sites[t]; break; }",
  "    }",
  "    var prevTicket = prevSite === null ? null : prevSite.open_ticket;",
  "    var ticket = site.open_ticket;",
  "    if (ticket !== null && (prevTicket === null || prevTicket.id !== ticket.id)) {",
  "      lines.push(ticket.id + ' opened · ' + site.site_id + ' · ' + ticket.priority);",
  "    }",
  "    if (ticket === null && prevTicket !== null) {",
  "      lines.push(prevTicket.id + ' resolved · ' + site.site_id);",
  "    }",
  "  }",
  "  return lines;",
  "}",
  "function kindClass(line) {",
  "  if (line.indexOf('raised to P1') !== -1 || line.indexOf('declared P1') !== -1) {",
  "    return 'k-crit';",
  "  }",
  "  if (line.indexOf('resolved') !== -1) return 'k-ok';",
  "  if (line.indexOf('declared') !== -1 || line.indexOf('lowered') !== -1) {",
  "    return 'k-warn';",
  "  }",
  "  if (line.indexOf('opened') !== -1) return 'k-accent';",
  "  return '';",
  "}",
  "function renderFeed(newCount) {",
  "  var host = byId('feed');",
  "  while (host.firstChild) host.removeChild(host.firstChild);",
  "  for (var i = 0; i < feedItems.length && i < 8; i++) {",
  "    var item = feedItems[i];",
  "    var cls = item.kind ? item.kind : '';",
  "    if (i < newCount) cls = (cls + ' fresh').trim();",
  "    var li = el('li', cls);",
  "    li.appendChild(el('span', 'ftext', item.text));",
  "    var time = el('span', 'mono ftime', rel(item.at));",
  "    time.setAttribute('data-at', String(item.at));",
  "    li.appendChild(time);",
  "    host.appendChild(li);",
  "  }",
  "}",
  "function applyBoard(prev, next) {",
  "  var incidents = 0, p1 = 0, tickets = 0, r, s;",
  "  for (r = 0; r < next.regions.length; r++) {",
  "    if (next.regions[r].incident !== null) {",
  "      incidents++;",
  "      if (next.regions[r].incident.priority === 'P1') p1++;",
  "    }",
  "  }",
  "  for (s = 0; s < next.sites.length; s++) {",
  "    if (next.sites[s].open_ticket !== null) tickets++;",
  "  }",
  "  byId('kInc').textContent = String(incidents);",
  "  byId('kP1').textContent = String(p1);",
  "  byId('kTix').textContent = String(tickets);",
  "  byId('p1Tile').classList.toggle('hot', p1 > 0);",
  "  byId('modeChip').textContent = 'actors: ' + next.actor_mode;",
  "  renderMap(next);",
  "  renderRegions(next, prev);",
  "  if (prev === null) {",
  "    feedItems.unshift({",
  "      text: 'live board synced · ' + next.sites.length + ' sites watched',",
  "      kind: '', at: Date.now() });",
  "    renderFeed(1);",
  "  } else {",
  "    var fresh = diffLines(prev, next);",
  "    for (var i = fresh.length - 1; i >= 0; i--) {",
  "      var dup = false;",
  "      for (var j = 0; j < feedItems.length; j++) {",
  "        if (feedItems[j].text === fresh[i]) { dup = true; break; }",
  "      }",
  "      if (!dup) {",
  "        feedItems.unshift({ text: fresh[i], kind: kindClass(fresh[i]), at: Date.now() });",
  "      }",
  "    }",
  "    feedItems = feedItems.slice(0, 8);",
  "    renderFeed(fresh.length);",
  "  }",
  "  updateAge();",
  "}",
].join("\n");
const JS_LIFE = [
  "/* polling: no overlap, hard timeout, keep the last board on failure */",
  "var staleBadge = byId('staleBadge');",
  "var hair = byId('hair');",
  "function kickHair() {",
  "  if (!hair) return;",
  "  hair.classList.remove('run');",
  "  void hair.offsetWidth;",
  "  hair.classList.add('run');",
  "}",
  "var polling = false;",
  "function poll() {",
  "  if (polling) { setTimeout(poll, POLL_MS); return; }",
  "  polling = true;",
  "  var ctrl = new AbortController();",
  "  var timer = setTimeout(function () { ctrl.abort(); }, FETCH_MS);",
  "  fetch('/ops/board', { signal: ctrl.signal, headers: { accept: 'application/json' } })",
  "    .then(function (res) {",
  "      if (!res.ok) throw new Error('http ' + res.status);",
  "      return res.json();",
  "    })",
  "    .then(function (next) {",
  "      var prev = board;",
  "      board = next;",
  "      generatedMs = Date.parse(next.generated_at) || Date.now();",
  "      applyBoard(prev, next);",
  "      kickHair();",
  "      if (staleBadge) staleBadge.hidden = true;",
  "    })",
  "    .catch(function () { if (staleBadge) staleBadge.hidden = false; })",
  "    .then(function () {",
  "      clearTimeout(timer);",
  "      polling = false;",
  "      setTimeout(poll, POLL_MS);",
  "    });",
  "}",
  "poll();",
  "/* operator drawer: token lives in sessionStorage only, sent as a bearer */",
  "var TOKEN_KEY = 'nocOpsToken';",
  "var tokenInput = byId('opsToken'), opsOut = byId('opsOut');",
  "try { tokenInput.value = sessionStorage.getItem(TOKEN_KEY) || ''; } catch (err) { /* none */ }",
  "tokenInput.addEventListener('input', function () {",
  "  try { sessionStorage.setItem(TOKEN_KEY, tokenInput.value); } catch (err) { /* none */ }",
  "});",
  "var OPS_ROUTES = {",
  "  reset: '/ops/reset',",
  "  stage: '/ops/stage-incident?region=riyadh-north',",
  "  ack: '/ops/ack?region=riyadh-north',",
  "  resolve: '/ops/resolve?region=riyadh-north',",
  "};",
  "Array.prototype.forEach.call(document.querySelectorAll('[data-op]'), function (btn) {",
  "  btn.addEventListener('click', function () {",
  "    var path = OPS_ROUTES[btn.getAttribute('data-op')];",
  "    if (!path) return;",
  "    opsOut.textContent = 'POST ' + path + ' …';",
  "    fetch(path, { method: 'POST', headers: {",
  "      authorization: 'Bearer ' + (tokenInput.value || '') } })",
  "      .then(function (res) {",
  "        return res.text().then(function (body) {",
  "          opsOut.textContent = res.status + ' ' + body;",
  "        });",
  "      })",
  "      .catch(function (err) { opsOut.textContent = 'failed: ' + err.message; });",
  "  });",
  "});",
  "})();",
].join("\n");

const APP_JS = [JS_CORE, JS_RENDER, JS_LIFE].join("\n");

function bodyMarkup(cards: string): string {
  return [
  "<telnyx-ai-agent agent-id=\"" + DEMO_AGENT_ID + "\"></telnyx-ai-agent>",
  "<div class=\"fx\" aria-hidden=\"true\">",
  "<span class=\"g g1\"></span><span class=\"g g2\"></span><span class=\"g g3\"></span>",
  "</div>",
  "<div class=\"fxGrid\" aria-hidden=\"true\"></div>",
  "<div class=\"fxNoise\" aria-hidden=\"true\"></div>",
  "<header class=\"top\">",
  "<div class=\"brand\"><strong class=\"mark\">NOC FRONT DOOR</strong>",
  "<span class=\"sub\">Najd Networks · 24/7 AI fault line</span></div>",
  "<div class=\"topRight\">",
  "<span class=\"live\"><span class=\"liveDot\"></span>LIVE</span>",
  "<span class=\"clock mono\" id=\"clock\">--:--:--</span>",
  "<span class=\"modeChip mono\" id=\"modeChip\">actors: …</span>",
  "</div>",
  "<span class=\"hair\" id=\"hair\"></span>",
  "</header>",
  "<main class=\"wrap\">",
  "<section class=\"panel left\">",
  "<h2>Talk to Sanad</h2>",
  "<div class=\"orbWrap\">",
  "<button type=\"button\" class=\"orb\" id=\"orb\" aria-label=\"Start a web call with Sanad\">",
  "<span class=\"orbConic\"></span><span class=\"pulse\"></span><span class=\"pulse p2b\"></span>",
  "<span class=\"bar b1\"></span><span class=\"bar b2\"></span><span class=\"bar b3\"></span>",
  "<span class=\"bar b4\"></span><span class=\"bar b5\"></span><span class=\"bar b6\"></span>",
  "<span class=\"bar b7\"></span>",
  "</button>",
  "</div>",
  "<p class=\"orbCap\" id=\"orbCap\">Tap to start a web call · allow your microphone</p>",
  "<p class=\"orbHint\">Tap the orb — or 'Talk to Sanad' bottom-right — the Telnyx launcher stays available.</p>",
  "<div class=\"cards\">" + cards + "</div>",
  "<div class=\"ribbon\">",
  "<p class=\"ribbonTitle\">How it works</p>",
  flowList(),
  "</div>",
  "</section>",
  "<section class=\"panel right\">",
  "<div class=\"boardHead\">",
  "<h2>NOC board</h2>",
  "<span class=\"stale\" id=\"staleBadge\" hidden>stale</span>",
  "</div>",
  "<div class=\"kpis\">",
  "<div class=\"kpi\"><span class=\"kLabel\">Open incidents</span>",
  "<span class=\"kNum\" id=\"kInc\">–</span></div>",
  "<div class=\"kpi\" id=\"p1Tile\"><span class=\"kLabel\">P1 incidents</span>",
  "<span class=\"kNum\" id=\"kP1\">–</span></div>",
  "<div class=\"kpi\"><span class=\"kLabel\">Open tickets</span>",
  "<span class=\"kNum\" id=\"kTix\">–</span></div>",
  "<div class=\"kpi\"><span class=\"kLabel\">Board age</span>",
  "<span class=\"kNum\" id=\"kAge\">–</span><span class=\"kSub\">since update</span></div>",
  "</div>",
  "<div class=\"mapPanel\">",
  "<div class=\"mapHead\"><span class=\"mapTitle\">KSA situation map</span>",
  "<span class=\"mapHint\">live telemetry</span></div>",
  mapSvg(),
  "</div>",
  "<div class=\"regions\" id=\"regions\"></div>",
  "<h3 class=\"feedTitle\">Event feed</h3>",
  "<ul class=\"feed\" id=\"feed\"></ul>",
  "<p class=\"panelFoot\">Live from Stateful Actors via /ops/board · refresh 5 s · data masked</p>",
  "</section>",
  "</main>",
  "<details class=\"drawer\" id=\"opsDrawer\">",
  "<summary>Operator</summary>",
  "<div class=\"drawerBody\">",
  "<label>OPS token<input type=\"password\" id=\"opsToken\" autocomplete=\"off\"></label>",
  "<div class=\"opsBtns\">",
  "<button type=\"button\" data-op=\"reset\">Reset demo</button>",
  "<button type=\"button\" data-op=\"stage\">Stage Riyadh North incident</button>",
  "<button type=\"button\" data-op=\"ack\">Acknowledge</button>",
  "<button type=\"button\" data-op=\"resolve\">Resolve</button>",
  "</div>",
  "<pre class=\"opsOut\" id=\"opsOut\"></pre>",
  "</div>",
  "</details>",
  "<footer class=\"foot\">",
  "<p>Built on Telnyx Voice AI · Edge Compute · KV · Stateful Actors · MCP — code authored by OpenCode on Telnyx Inference</p>",
  "<p>Calls are recorded and handled by an AI assistant.</p>",
  "</footer>",
  ].join("\n");
}

function pinChip(scenario: GuideScenario | undefined): string {
  if (scenario === undefined) {
    return `<span class="pin-miss">${GUIDE_FALLBACK}</span>`;
  }
  return `<button type="button" class="pin-chip" data-pin="${scenario.pin}">PIN ${scenario.pin} · click to copy</button>`;
}

function scenarioCard(
  num: number,
  title: string,
  say: string,
  watch: string,
  chip: string,
): string {
  const parts = [
    `<article class="card">`,
    `<span class="cardNum">${num}</span>`,
    `<h3>${title}</h3>`,
    `<p class="say">Say: <q>${say}</q></p>`,
    `<p class="watch">Watch: ${watch}</p>`,
  ];
  if (chip.length > 0) parts.push(chip);
  parts.push(`</article>`);
  return parts.join("");
}

export function renderDemoPage(guide: DemoGuide | null): string {
  const byKey = new Map<string, GuideScenario>();
  for (const scenario of guide?.scenarios ?? []) byKey.set(scenario.key, scenario);
  const cards = [
    scenarioCard(
      1,
      "Join the incident",
      "We are fully offline at the Al Yasmin branch in Riyadh North — site R U H one one four. I need to report an outage and join the ongoing incident.",
      "the Riyadh North incident turn P1 at 3 branches.",
      pinChip(byKey.get("join")),
    ),
    scenarioCard(
      2,
      "Open a new ticket",
      "Site J E D zero zero seven in Jeddah is down — phones and internet are offline. Please open a ticket for us.",
      "a new ticket appear under the Jeddah region.",
      pinChip(byKey.get("new")),
    ),
    scenarioCard(
      3,
      "Lockout &amp; human",
      "My PIN is not working — try a wrong PIN three times to hear the lock, then ask for a human engineer.",
      "Sanad lock the site after three wrong PINs, then page the on-call engineer.",
      "",
    ),
  ].join("");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>NOC Front Door — Live NOC wall</title>
<style>
${CSS}
</style>
</head>
<body>
${bodyMarkup(cards)}
<script async src="${WIDGET_SCRIPT_URL}"></script>
<script>
${APP_JS}
</script>
</body>
</html>
`;
}
